version: "2"
services:
  animlist:
    build: .
    hostname: animlist
    environment:
      mongoDbURL: mongodb://admin:apassworttochange@mongodb/animlist?authSource=admin
    expose:
      - 3000
    ports:
      - 1234:3000
    links:
      - mongodb
  mongodb:
    image: mongo:4
    hostname: mongodb
    expose:
      - 27017
    ports:
      - 3507:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: apassworttochange
    command: mongod --port 27017
    volumes:
      - ./mongo-volume:/data
