version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.docker/config.json:/config.json
    command: --interval 10 --label-enable

  animlist:
    image: docker.pkg.github.com/julienkeiff/docker-registry/animlist:latest
    hostname: animlist
    restart: always
    environment:
      mongoDbURL: mongodb://admin:apassworttochange@mongodb/animlist?authSource=admin
    expose:
      - 3000
    ports:
      - 1234:3000
    links:
      - mongodb
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  mongodb:
    image: mongo:4
    hostname: mongodb
    restart: always
    expose:
      - 27017
    ports:
      - 3507:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: apassworttochange
    command: mongod --port 27017
    volumes:
      - ./mongo-volume:/data
